CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL
);
CREATE TABLE Shop (
    ShopID INT AUTO_INCREMENT PRIMARY KEY,
    ShopName VARCHAR(255) UNIQUE NOT NULL,
    Location VARCHAR(255)
);
CREATE TABLE List (
    ListID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ShopID INT NOT NULL,
    ListName VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID),
    FOREIGN KEY (ShopID) REFERENCES Shop(ShopID)
);
CREATE TABLE Item (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    ListID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    Purchased BOOLEAN NOT NULL,
    FOREIGN KEY (ListID) REFERENCES List(ListID),
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);
CREATE TABLE Product (
    ProductID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryID INT NOT NULL,
    BrandID INT NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Description TEXT,
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID),
    FOREIGN KEY (BrandID) REFERENCES Brand(BrandID)
);
CREATE TABLE Brand (
    BrandID INT AUTO_INCREMENT PRIMARY KEY,
    BrandName VARCHAR(255) UNIQUE NOT NULL
);
CREATE TABLE Category (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(255) UNIQUE NOT NULL
);
CREATE TABLE Review (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ShopID INT NOT NULL,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comment TEXT,
    Date DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID),
    FOREIGN KEY (ShopID) REFERENCES Shop(ShopID)
);